version: 2

updates:
  - package-ecosystem: "cargo"
    groups:
      shuttle:
        patterns:
          - "shuttle-*"
        update-types:
          - "patch"
          - "minor"
          - "major"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
