name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable
    - name: Build
      run: |
        cargo build --verbose
        cargo build --verbose --all-features
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --verbose --all-features
